groups:
- name: general
  rules:

  - alert: local-sampleapp-errors
    expr: count(count by (action, controller, traceIdentifier) (samplehttp{quantile="0.99",service="sampleapp",statusCode!=200})) > 1
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "Http Request Error when calling  {{ $labels.controller }}/{{ $labels.controller }}  in sampleapp on local"
      description: ""

  - alert: local-sampleapp-healthcheck
    expr: absent(samplehc{service="sampleapp"} == 1)
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "sampleapp is not healthy on local"
      description: ""

  - alert: local-sampleapp-slow
    expr: max by(controller,action) (samplehttp{quantile="0.99",service="sampleapp"}) > 0.01
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "The endpoint  {{ $labels.controller }}/{{ $labels.controller }}  in sampleapp on local is too slow"
      description: ""

  - alert: local-sampleapp-masstransit-errors
    expr: count(count by (messageType) (samplemasstransit{quantile="0.99",service="sampleapp",success="False"})) > 1
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "Masstransit Error when processing  {{ $labels.messageType }}  in sampleapp on local"
      description: ""

  - alert: local-sampleapp-masstransit-errors
    expr: count(count by (commandText) (sampleef{quantile="0.99",service="sampleapp",success="False"})) > 1
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "EntityFrameworkCore Error when executing  {{ $labels.commandText }}  in sampleapp on local"
      description: ""
