apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true

- name: Jaeger
  type: jaeger
  orgId: 1
  access: server
  url: http://jaeger:16686
  editable: false
