language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- yarn build:core
- yarn build:native
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- TAG=linux-x64-20200618
- docker tag profiler:native ababoshin/dotnetcoreprofiler:$TAG
- docker push ababoshin/dotnetcoreprofiler:$TAG
- yarn build:llvm
- TAG=llvm-10
- docker tag profiler:llvm ababoshin/dotnetcoreprofiler:$TAG
- docker push ababoshin/dotnetcoreprofiler:$TAG

script:
- echo "done"
