language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- TAG=linux-x64-20201231
- yarn tests:all
- yarn build:core
- yarn build:native:nuget
- yarn build:metricproxy
- docker tag metricproxy:native ababoshin/metricproxy:$TAG
- docker push ababoshin/metricproxy:$TAG
- yarn build:metricproxy:nuget

script:
- echo "done"
