language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# - yarn build:llvm
# - TAG=llvm-10
# - docker tag profiler:llvm ababoshin/dotnetcoreprofiler:$TAG
# - docker push ababoshin/dotnetcoreprofiler:$TAG
- yarn build:core
# - yarn build:native
- yarn build:native:nuget
# - TAG=linux-x64-20200831
# - docker tag profiler:native ababoshin/dotnetcoreprofiler:$TAG
# - docker push ababoshin/dotnetcoreprofiler:$TAG

script:
- echo "done"
