language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- TAG=llvm-10
- docker pull ababoshin/dotnetcoreprofiler:$TAG
- docker tag ababoshin/dotnetcoreprofiler:$TAG profiler:llvm
#- yarn build:llvm
#- docker tag profiler:llvm ababoshin/dotnetcoreprofiler:$TAG
#- docker push ababoshin/dotnetcoreprofiler:$TAG
- yarn tests:all
- yarn build:core
- yarn build:native:nuget

script:
- echo "done"
