language: node_js
node_js:
  - 14

services:
  - docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- yarn tests:all
- yarn build:core
- yarn build:native:nuget

script:
- echo "done"
