FROM mcr.microsoft.com/dotnet/core/sdk:2.1.701 as build

COPY src src

RUN dotnet publish -c Release -o /interception src/Interception/Interception.csproj
RUN dotnet publish -c Release -o /interception src/Interception.DeadlockDetection/Interception.DeadlockDetection.csproj
RUN dotnet publish -c Release -o /interception src/Interception.Generator/Interception.Generator.csproj
RUN cd /interception && dotnet Interception.Generator.dll -a Interception.dll,Interception.Core.dll,Interception.DeadlockDetection.dll -p /profiler -o /interception/profiler.json && cat /interception/profiler.json
