init:
  image: ababoshin/kubernetes-cert-signer:20210330-1

mutator:
  image: ababoshin/monitoring-mutator:20210331-7
  imagePullPolicy: Never

config: |
  {
    "env": [
      {
        "name": "aspnetcore_metrics__enabled",
        "value": "true"
      },
      {
        "name": "aspnetcore_metrics__name",
        "value": "incoming"
      },
      {
        "name": "httphandler_metrics__enabled",
        "value": "true"
      },
      {
        "name": "httphandler_metrics__name",
        "value": "outgoing"
      },
      {
        "name": "service__name",
        "value": "sampleapp"
      },
      {
        "name": "METRIC_PROXY__UDS",
        "value": "/var/metricproxy"
      },
      {
        "name": "METRIC_PROXY_SERVER__UDS",
        "value": "/var/metricproxy"
      },
      {
        "name": "METRIC_PROXY_SERVER__STATSD",
        "value": "statsd-prometheus-statsd-exporter:9125"
      },
      {
        "name": "METRIC_PROXY_SERVER__LOG_LEVEL",
        "value": "info"
      },
      {
        "name": "CORECLR_ENABLE_PROFILING",
        "value": "1"
      },
      {
        "name": "CORECLR_PROFILER",
        "value": "{585022b6-31e9-4ddf-b35d-3c256d0a16f3}"
      },
      {
        "name": "CORECLR_PROFILER_PATH",
        "value": "/profiler/DotNetCoreProfiler.so"
      },
      {
        "name": "PROFILER_CONFIGURATION",
        "value": "/profiler/profiler.json"
      },
      {
        "name": "PROFILER_LOG_LEVEL",
        "value": "INFO"
      }
    ],
    "volumeMounts": [
      {
        "mountPath": "/profiler",
        "name": "profiler",
        "readOnly": true
      }
    ],
    "volumes": [
      {
        "name": "profiler",
        "emptyDir": {}
      }
    ],
    "initContainers": [
      {
        "name": "copy-files",
        "image": "sample:init",
        "imagePullPolicy": "Never",
        "volumeMounts": [
          {
            "mountPath": "/profiler",
            "name": "profiler"
          }
        ],
        "command": [
          "/bin/sh"
        ],
        "args": [
          "-c",
          "cp /interceptor/* /profiler/"
        ]
      }
    ]
  }
