apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      inject-monitoring: "true"
  replicas: 1
  template:
    metadata:
      labels:
        inject-monitoring: "true"
    spec:
      containers:
      - name: sampleapp
        image: sample:app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: SERVICE_URL
          value: "http://sampleapp2:6000"
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
