apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      inject-monitoring: "true"
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        inject-monitoring: "true"
        app: app1
    spec:
      containers:
      - name: sampleapp
        image: sample:app
        imagePullPolicy: Never
        env:
        - name: SERVICE_URL
          value: "http://app2:5000"
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      inject-monitoring: "true"
      app: app2
  serviceName: app2
  replicas: 1
  template:
    metadata:
      labels:
        inject-monitoring: "true"
        app: app2
    spec:
      containers:
      - name: sampleapp
        image: sample:app
        imagePullPolicy: Never
        env:
        - name: SERVICE_URL
          value: "http://app1:5000"
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app2
---
