version: '3.3'

services:
  sampleapp:
    image: samples:quartz
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5000"
      JAEGER_AGENT_HOST: "jaeger"
      JAEGER_AGENT_PORT: "6831"
      JAEGER_SAMPLER_TYPE: "const"
      JAEGER_SERVICE_NAME: "sampleapp"
      quartz_metrics__name: "scheduled_job"
      quartz_metrics__enabled: "true"
      service__name: "sampleapp"
      tracing__collector: "jaeger"
      LOG_LEVEL: "Information"

  jaeger:
    image: jaegertracing/all-in-one:1.20.0
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
