{
 "title": "Interception Metrics",
 "time": { "from": "2020-06-12T10:51:24.693Z", "to": "2020-06-12T22:51:24.693Z" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(interception, service)"
   }
  ]
 },
 "panels": [
  { "title": "Execution Time Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Expensive incoming HTTP Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(ControllerName, ActionName,service) (interception{quantile=\"0.99\",service=~\"$service\",metric=\"incoming\"})))"
    }
   ]
  },
  {
   "title": "Expensive outgoing HTTP Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(http_url,service) (interception{quantile=\"0.99\",service=~\"$service\",metric=\"outgoing\"})))"
    }
   ]
  },
  {
   "title": "Expensive Masstransit Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(Consumer,service) (interception{quantile=\"0.99\",service=~\"$service\",metric=\"masstransit_consume\"})))"
    }
   ]
  },
  {
   "title": "Expensive Scheduled Job Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(topk(100, max by(task,service) (interception{quantile=\"0.99\",service=~\"$service\",metric=\"scheduled_job\"})))"
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Error incoming HTTP Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "interception{quantile=\"0.99\",service=~\"$service\",metric=\"incoming\",error=\"True\"}"
    }
   ]
  },
  {
   "title": "Error outgoing HTTP Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "interception{quantile=\"0.99\",service=~\"$service\",metric=\"outgoing\",error=\"True\"}"
    }
   ]
  },
  {
   "title": "Error Masstransit Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "interception{quantile=\"0.99\",service=~\"$service\",metric=\"masstransit_consume\",error=\"True\"}"
    }
   ]
  },
  {
   "title": "Error Scheduled Jobs Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "interception{quantile=\"0.99\",service=~\"$service\",metric=\"scheduled_job\",error=\"True\"}"
    }
   ]
  }
 ]
}