apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mutator.fullname" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "mutator.fullname" . }}"
data:
  config: |
{{ .Values.config | indent 4 -}}

