apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "mutator.fullname" . }}-app
  labels:
    app: {{ template "mutator.fullname" . }}-app
    chart: {{ template "mutator.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
webhooks:
  - name: monitoring-mutator.default.svc.cluster.local
    clientConfig:
      caBundle: "ZW1wdHk="
      service:
        name: {{ template "mutator.fullname" . }}-app
        namespace: default
        path: "/validate"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: NoneOnDryRun
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    {{- if .Values.namespaceSelector }}
    namespaceSelector:
    {{- if .Values.namespaceSelector.matchLabels }}
      matchLabels:
  {{ toYaml .Values.namespaceSelector.matchLabels | indent 6 }}
    {{- end }}
      matchExpressions:
      {{- if .Values.namespaceSelector.matchExpressions }}
  {{ toYaml .Values.namespaceSelector.matchExpressions | indent 4 }}
      {{- end }}
    {{- end }}
    {{- if .Values.objectSelector }}
    objectSelector:
    {{- if .Values.objectSelector.matchLabels }}
      matchLabels:
  {{ toYaml .Values.objectSelector.matchLabels | indent 6 }}
    {{- end }}
      matchExpressions:
      {{- if .Values.objectSelector.matchExpressions }}
  {{ toYaml .Values.objectSelector.matchExpressions | indent 4 }}
      {{- end }}
    {{- end }}
