apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mutator.fullname" . }}-cert-ca
  labels:
    app: {{ template "mutator.fullname" . }}-app
    chart: {{ template "mutator.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "mutator.fullname" . }}-cert-ca-cluster-role
  labels:
    app: {{ template "mutator.fullname" . }}-app
    chart: {{ template "mutator.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "get", "create", "patch", "update" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests" ]
    verbs: [ "get", "create", "delete" , "list", "watch" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests/approval" ]
    verbs: [ "update" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "signers" ]
    resourceNames: [ "kubernetes.io/*"]
    verbs: [ "approve" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "get", "patch","update"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mutator.fullname" . }}-cert-ca-cluster-role-binding
  labels:
    app: {{ template "mutator.fullname" . }}-app
    chart: {{ template "mutator.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mutator.fullname" . }}-cert-ca-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "mutator.fullname" . }}-cert-ca
    namespace: default
