apiVersion: v1
kind: Service
metadata:
  name: {{ template "mutator.fullname" . }}-app
  labels:
    app: {{ template "mutator.fullname" . }}-app
    chart: {{ template "mutator.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: {{ template "mutator.fullname" . }}-app
